### ISSUE TITLE
speed / cache?

### ISSUE THREAD

**Issue by floswald** [piever/Remark.jl#12]
one thing i noticed is that it takes quite some time to rebuild the presentation. is there any way to shortcut some steps with a caching mechanism maybe?

**Comment by piever** [comment]
That's mostly due to Documenter:

```julia
julia> @time slideshowdir = Remark.slideshow("/home/pietro/Documents/presentation/juliacon2018/markdown.md", "/home/pietro/Documents/presentation/juliacon2018/", documenter = true)
Documenter: setting up build directory.
Documenter: expanding markdown templates.
Documenter: building cross-references.
Documenter: running document checks.
 > checking for missing docstrings.
 > running doctests.
 > checking footnote links.
Documenter: populating indices.
Documenter: rendering document.
Documenter: copying assets to build directory.
  2.144362 seconds (1.23 M allocations: 114.019 MiB, 1.37% gc time)
"/home/pietro/Documents/presentation/juliacon2018"

julia> @time slideshowdir = Remark.slideshow("/home/pietro/Documents/presentation/juliacon2018/markdown.md", "/home/pietro/Documents/presentation/juliacon2018/", documenter = false)
  0.006304 seconds (2.60 k allocations: 177.859 KiB)
"/home/pietro/Documents/presentation/juliacon2018"
```

(though you'll need to pull master again for the `documenter=false` option, it was only just fixed). 

We could perhaps ask over at Documenter if there are ways to speed things up.

**Comment by floswald** [comment]
i see. so what happens when i set `documenter=false`? i can still use `@example` in my slides?

**Comment by piever** [comment]
The markdown is shown as is, meaning in the resulting presentation it will still say `@example` and won't show the result. I'd love it if there were a more efficient way to just run the markdown inline but I don't know any,
