### ISSUE TITLE
Copying of extra files to build directory

### ISSUE THREAD

**Issue by fredrikekre** [piever/Remark.jl#22]
I have a couple of png files located next to my source file, and currently I have to manually copy these to the correct location after each build. Would be convenient to somehow mark file that should be copied.

**Comment by piever** [comment]
How does Documenter do it? I'm not sure what's the user friendly way to do this. I could maybe just copy a `assets` folder that lives next to the index file if it exists in an `assets` folder next to `index.html` in the build. So one just has to take the habit to put things inside `assets`.

**Comment by fredrikekre** [comment]
Documenter copies everything in the `src` directory. But for Remark, where you just give one one specific file as input that does nto really make sense. Maybe just an assets kwargs, where you can include a source tree to copy.

**Comment by oxinabox** [comment]
#42

**Comment by piever** [comment]
Fixed by #42
