### ISSUE TITLE
tag a new release?

### ISSUE THREAD

**Issue by korsbo** [piever/Remark.jl#30]
Hi, I just installed Remark.jl and I'm curious to try it out. 

However, during the installation process, I found that I could not add the latest released version since it gives me unsatisfiable requirements. It works fine when using the master branch, so it may be time for a new release. 

Cheers!

**Comment by piever** [comment]
Ups, yes, latest release is kind of broken, I had forgotten to tag a new one. I've just tagged an updated version (https://github.com/JuliaRegistries/General/pull/9710), thanks for the reminder!
