### ISSUE TITLE
unexpected xml tag `<?xml version="1.0" encoding="utf-8"?>` occurs

### ISSUE THREAD

**Issue by terasakisatoshi** [piever/Remark.jl#32]
`<?xml version="1.0" encoding="utf-8"?>` occurs when I insert code related to gr backend Plots 

```julia
using Plots
gr() # switch to GR backend
plot(sin)
```

![image](https://user-images.githubusercontent.com/16760547/78981345-b27c8700-7b5a-11ea-9927-d5760eaf10d0.png)

on the other hand, when I switch to pyplot backend I get no issue. 🤔

**Comment by piever** [comment]
Thanks for reporting this! Somehow the svg generated by GR also includes that xml tag, which does not appear in html files, but markdown gets confused with it.

I wonder where this should be fixed exactly, maybe at GR?

**Comment by piever** [comment]
A better solution to this would probably be to implement something like https://github.com/piever/Remark.jl/issues/22, and during the build step saving the svg to a file rather than directly into the generated html.

**Comment by terasakisatoshi** [comment]
- Thank you for your advice.
- I've modified my source code as follow. It saves the plotting result using `savefig` and display the result using markdown syntax `![](path/to/img/png)`

```
using Plots
gr()
x = -π:0.01:π
p1 = plot(x, cos.(x))
p2 = plot(x, sin.(x))
plot(p1, p2, layout=(2,1))
savefig("saved.png") #hide

# ![not found](saved.png)
```

The result should be as follow:

![Screenshot from 2020-04-14 03-18-26](https://user-images.githubusercontent.com/16760547/79147345-c47e5400-7dfe-11ea-8d79-d074537d07d6.png)

**Comment by terasakisatoshi** [comment]
I've confirmed the workaround above solves my problem: 
- https://terasakisatoshi.github.io/MathSeminar.jl/remark/build/#5

**Comment by piever** [comment]
Thanks for verifying that it works! I think this should be the preferred approach anyways, I'll add it to the docs.
