### ISSUE TITLE
Parsing error in image html tag

### ISSUE THREAD

**Issue by yuehhua** [piever/Remark.jl#34]
I try to insert an image in my slides. I tried using html tag as follow:

```
<img src="../../sphx_glr_plot_compare_methods_0011.png">
```

But I found it parse the file name in html into: `sphx*glr*plot*compare*methods_0011.png`

This cause the image display fail on slide show.

**Comment by piever** [comment]
Are you using the default value of keyword arguments in `slideshow`, i.e. `documenter=true`? Could you try passing `documenter=false`, to see if it is a problem of Documenter not supporting raw HTML?

For now, you could use markdown image syntax, i.e. 

```md
![alternative text](../../sphx_glr_plot_compare_methods_0011.png)
```

**Comment by yuehhua** [comment]
`documenter=false` works! Thank you.
Why I use HTML tag here? I want to adjust the width and height but markdown doesn't provide features like that.
