### ISSUE TITLE
Read only files

### ISSUE THREAD

**Issue by tlienart** [piever/Remark.jl#48]
When using the example in the readme to create a presentation, the files are read only as far as I can see e.g.:

`juliapres/presentation/src`

```
total 8
drwxr-xr-x  3 tlienart    96B Sep 13 14:49 .
drwxr-xr-x  5 tlienart   160B Sep 13 14:50 ..
-r--r--r--  1 tlienart   367B Sep 13 14:49 index.md
```

I think it's Pkg that does that when copying files over (I have a similar issue with FranklinTemplates), one way is to read/write these files, another is to `chmod(file, 0o644)` maybe

**Comment by piever** [comment]
Yes, I had noticed, this was a bit annoying. Reading and writing the files seems like a good fix. Should be fixed by #49
