### ISSUE TITLE
automatically resize plots?

### ISSUE THREAD

**Issue by floswald** [piever/Remark.jl#9]
I changed the Plots backend to `gr` and ended up with a huge plot on the slide:

````
# A plot

```@example index
using Plots; gr()
Plots.plot(rand(10))
savefig("statplot.png");
```

# ![](statplot.png)
````

is there a way to automatically resize the plot? it's weird that with pyplot it has exactly the right size.

**Comment by piever** [comment]
I think there used to be some issues with Plots and GR concerning png size (some dpi things I don't fully understand, see for example https://github.com/barche/QML.jl/issues/53

I think saving to svg is in general a better option, does that work better for you?

**Comment by floswald** [comment]
works perfectly with .svg! in that case you can forget about my PR #11 
all of those things would probably be good to add to a wiki.

**Comment by piever** [comment]
Btw, will you be using julia 1.0 or 0.6? I'm a bit unsure whether I should merge #8 : if you plan on using 0.6 would breaking 0.6 on master make it harder for you to contribute?

**Comment by floswald** [comment]
good question! you know what, let's take the plunge. that course will restart only in january, so plenty of time for julia 1.0 packages to get rolling. I won't use Remark.js for an upcoming presentation in a hyper secure government agency in 2 weeks time (god knows what happens if you want to use javascript!)
